// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzFbtzSgHrQ8LoOL9WM45CYUywlx74M4w',
    appId: '1:693567023286:web:742cc7902bcc5c2d629e17',
    messagingSenderId: '693567023286',
    projectId: 'emailapp-f6dc0',
    authDomain: 'emailapp-f6dc0.firebaseapp.com',
    storageBucket: 'emailapp-f6dc0.firebasestorage.app',
    measurementId: 'G-ZN3YCQGZG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKn7KFG7-EV6YB1nbFZoPd74C22nkCmmk',
    appId: '1:693567023286:android:6b91362e9a9110d7629e17',
    messagingSenderId: '693567023286',
    projectId: 'emailapp-f6dc0',
    storageBucket: 'emailapp-f6dc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXlOphPzuyGo17mtHnhnIu8p6JJYq6BfU',
    appId: '1:693567023286:ios:d186c3afc759e122629e17',
    messagingSenderId: '693567023286',
    projectId: 'emailapp-f6dc0',
    storageBucket: 'emailapp-f6dc0.firebasestorage.app',
    iosClientId: '693567023286-bonma88daa2v80qff6va2ku1ap5t9umm.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailSendingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXlOphPzuyGo17mtHnhnIu8p6JJYq6BfU',
    appId: '1:693567023286:ios:d186c3afc759e122629e17',
    messagingSenderId: '693567023286',
    projectId: 'emailapp-f6dc0',
    storageBucket: 'emailapp-f6dc0.firebasestorage.app',
    iosClientId: '693567023286-bonma88daa2v80qff6va2ku1ap5t9umm.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailSendingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzFbtzSgHrQ8LoOL9WM45CYUywlx74M4w',
    appId: '1:693567023286:web:742cc7902bcc5c2d629e17',
    messagingSenderId: '693567023286',
    projectId: 'emailapp-f6dc0',
    authDomain: 'emailapp-f6dc0.firebaseapp.com',
    storageBucket: 'emailapp-f6dc0.firebasestorage.app',
    measurementId: 'G-ZN3YCQGZG8',
  );
}
